# Generated by Django 4.2.1 on 2023-05-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_task_taskhistory_task_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskhistory',
            old_name='task_id',
            new_name='task',
        ),
    ]
